[colors]
background = "#1E1D2F"
foreground = "#D9E0EE"
selection_bg = "#302D41"
selection_fg = "#F5C2E7"
cursor_bg = "#ABE9B3"
cursor_fg = "#1E1D2F"
cursor_border = "#ABE9B3"

#          Black,     Red,       Green,     Yellow,    Blue,      Magenta,   Cyan,      White
ansi =    ["#302D41", "#DDB6F2", "#ABE9B3", "#FAE3B0", "#96CDFB", "#F5C2E7" ,"#DDB6F2" ,"#D9E0EE"]
brights = ["#575268", "#E8A2AF", "#B5E8E0", "#F8BD96", "#89DCEB", "#C9CBFF", "#F5E0DC", "#C3BAC6"]
