[colors]
background = "#1E1E28"
foreground = "#D7DAE0"
selection_bg = "#2D293B"
selection_fg = "#F0AFE1"
cursor_bg = "#B3E1A3"
cursor_fg = "#EADDA0"
cursor_border = "#B3E1A3"

ansi = ["#6E6C7C", "#E28C8C", "#B3E1A3", "#EADDA0", "#A4B9EF", "#C6AAE8" ,"#F0AFE1" ,"#D7DAE0"]
brights = ["#6E6C7C", "#E28C8C", "#B3E1A3", "#EADDA0", "#A4B9EF", "#C6AAE8", "#F0AFE1", "#D7DAE0"]
